package com.example.ui.screens.tools

data class OfflineDuaItem(val id: Int, val title: String, val asset: String)

val OFFLINE_DUA_LIST = listOf(
    OfflineDuaItem(1, "দো'আর অর্থ", "dua_001.html"),
    OfflineDuaItem(2, "দো'আ কবুলের সময় ও স্থান", "dua_002.html"),
    OfflineDuaItem(3, "দো'আ করার আদব বা বৈশিষ্ট্য", "dua_003.html"),
    OfflineDuaItem(4, "সকাল-সন্ধ্যায় পঠিতব্য দো'আ সমূহ", "dua_004.html"),
    OfflineDuaItem(5, "শোয়ার দো'আ", "dua_005.html"),
    OfflineDuaItem(6, "পার্শ্ব পরিবর্তনের দো'আ", "dua_006.html"),
    OfflineDuaItem(7, "নিদ্রাবস্থায় ভয় পেয়ে অস্থির হ'লে দো'আ", "dua_007.html"),
    OfflineDuaItem(8, "নিদ্রাবস্থায় ভাল বা মন্দ স্বপ্ন দেখলে করণীয়", "dua_008.html"),
    OfflineDuaItem(9, "শয্যা ত্যাগের দো'আ সমূহ", "dua_009.html"),
    OfflineDuaItem(10, "010 জ্ঞান বৃদ্ধির দো'আ", "dua_010.html"),
    OfflineDuaItem(11, "011বিপদ-মুসিবতে পড়লে দো'আ", "dua_011.html"),
    OfflineDuaItem(12, "012ঋণ পরিশোধ ও দুশ্চিন্তা থেকে মুক্তির দো'আ", "dua_012.html"),
    OfflineDuaItem(13, "মোরগ, গাধা ও কুকুরের ডাক শুনে দো'আ", "dua_013.html"),
    OfflineDuaItem(14, "কাপড় পরিধানের দো'আ", "dua_014.html"),
    OfflineDuaItem(15, "নতুন কাপড় পরিধানের দো'আ", "dua_015.html"),
    OfflineDuaItem(16, "পায়খানায় প্রবেশের দো'আ", "dua_016.html"),
    OfflineDuaItem(17, "পায়খানা হ'তে বের হওয়ার দো'আ", "dua_017.html"),
    OfflineDuaItem(18, "বাড়ী থেকে বের হওয়ার দো'আ", "dua_018.html"),
    OfflineDuaItem(19, "মসজিদের দিকে গমনের দো'আ", "dua_019.html"),
    OfflineDuaItem(20, "মসজিদে প্রবেশ করা ও বের হওয়ার দো'আ", "dua_020.html"),
    OfflineDuaItem(21, "ইক্বামতের জবাব", "dua_021.html"),
    OfflineDuaItem(22, "ইমাম ও মুয়াযযিনের জন্য দো'আ", "dua_022.html"),
    OfflineDuaItem(23, "তাকবীরে তাহরীমার পর পঠিত দো'আ সমূহ", "dua_023.html"),
    OfflineDuaItem(24, "রুকূর দো'আ সমূহ", "dua_024.html"),
    OfflineDuaItem(25, "রুকূ হ'তে উঠার দো'আ", "dua_025.html"),
    OfflineDuaItem(26, "সিজদার দো'আ", "dua_026.html"),
    OfflineDuaItem(27, "দুই সিজদার মাঝের দো'আ", "dua_027.html"),
    OfflineDuaItem(28, "তেলাওয়াতে সিজদার দো'আ", "dua_028.html"),
    OfflineDuaItem(29, "রাসূল (ছাঃ)-এর প্রতি দরূদ পাঠ", "dua_029.html"),
    OfflineDuaItem(30, "সালাম ফিরানোর পূর্বের দো'আ সমূহ", "dua_030.html"),
    OfflineDuaItem(31, "সালাম ফিরানোর পর পঠিত দো'আ সমূহ", "dua_031.html"),
    OfflineDuaItem(32, "কেউ দো'আ চাইলে কি বলতে হবে?", "dua_032.html"),
    OfflineDuaItem(33, "বাসর রাতে স্বামী-স্ত্রী এক সঙ্গে ছালাত আদায়ের পর দো'আ", "dua_033.html"),
    OfflineDuaItem(34, "বাড়ীতে প্রবেশের দো'আ", "dua_034.html"),
    OfflineDuaItem(35, "চিন্তা দূর করার দো'আ", "dua_035.html"),
    OfflineDuaItem(36, "বিপদাপদের দো'আ", "dua_036.html"),
    OfflineDuaItem(37, "শত্রু এবং শক্তিধর ব্যক্তির সাক্ষাতকালে দো'আ", "dua_037.html"),
    OfflineDuaItem(38, "বাচ্চাদের জন্য পরিত্রাণ চাওয়ার দো'আ", "dua_038.html"),
    OfflineDuaItem(39, "রোগী দেখার দো'আ", "dua_039.html"),
    OfflineDuaItem(40, "বিভিন্ন রোগে ঝাড়-ফুঁকের কয়েকটি দো'আ", "dua_040.html"),
    OfflineDuaItem(41, "জীবনের নিরাশার সময় বলবে", "dua_041.html"),
    OfflineDuaItem(42, "যে কোন বিপদে পতিত ব্যক্তির দো'আ", "dua_042.html"),
    OfflineDuaItem(43, "মৃত ব্যক্তির চোখ বন্ধ করার সময় পঠিত দো'আ", "dua_043.html"),
    OfflineDuaItem(44, "মৃত ব্যক্তিকে দাফন করার পর দো'আ", "dua_044.html"),
    OfflineDuaItem(45, "মেঘের গর্জন শুনলে পঠিত দো'আ", "dua_045.html"),
    OfflineDuaItem(46, "বৃষ্টি প্রার্থনার দো'আ সমূহ", "dua_046.html"),
    OfflineDuaItem(47, "বৃষ্টি বন্ধের দো'আ", "dua_047.html"),
    OfflineDuaItem(48, "নতুন চাঁদ দেখে দো'আ", "dua_048.html"),
    OfflineDuaItem(49, "মেযবানের জন্য মেহমানের দো'আ", "dua_049.html"),
    OfflineDuaItem(50, "যে পানাহার করাল তার জন্য দো'আ", "dua_050.html"),
    OfflineDuaItem(51, "নতুন ফল দেখার পর পঠিত দো'আ", "dua_051.html"),
    OfflineDuaItem(52, "নব দম্পতির জন্য দো'আ", "dua_052.html"),
    OfflineDuaItem(53, "নতুন স্ত্রী গ্রহণ অথবা চতুষ্পদ জন্তু ক্রয়ের সময়", "dua_053.html"),
    OfflineDuaItem(54, "স্ত্রী সহবাসের দো'আ", "dua_054.html"),
    OfflineDuaItem(55, "ক্রোধ দমনের দো'আ", "dua_055.html"),
    OfflineDuaItem(56, "বিপন্ন লোককে দেখে দো'আ", "dua_056.html"),
    OfflineDuaItem(57, "মজলিসের মধ্যে পঠিতব্য দো'আ", "dua_057.html"),
    OfflineDuaItem(58, "মজলিসের কাফফারা", "dua_058.html"),
    OfflineDuaItem(59, "কুরআন তেলাওয়াত ও মজলিস শেষের দো'আ", "dua_059.html"),
    OfflineDuaItem(60, "কেউ সম্পদ দান করার জন্য পেশ করলে তার জন্য দো'আ", "dua_060.html"),
    OfflineDuaItem(61, "শিরক থেকে বাঁচার দো'আ", "dua_061.html"),
    OfflineDuaItem(62, "পশুর পিঠে অথবা যানবাহনে আরোহণের দো'আ", "dua_062.html"),
    OfflineDuaItem(63, "সফরের দো'আ", "dua_063.html"),
    OfflineDuaItem(64, "গ্রামে বা শহরে প্রবেশের দো'আ", "dua_064.html"),
    OfflineDuaItem(65, "বাজারে প্রবেশের দো'আ", "dua_065.html"),
    OfflineDuaItem(66, "সফরকারীর জন্য গৃহে অবস্থানকারীদের দো'আ", "dua_066.html"),
    OfflineDuaItem(67, "কেউ প্রশংসা করলে কি বলবে?", "dua_067.html"),
    OfflineDuaItem(68, "আশ্চর্যজনক অবস্থায় ও আনন্দের সময় পঠিতব্য দো'আ", "dua_068.html"),
    OfflineDuaItem(69, "হাঁচিদাতা ও শ্রোতার জন্য পঠিতব্য দো'আ", "dua_069.html"),
    OfflineDuaItem(70, "অমুসলিমদের হাঁচির জবাব", "dua_070.html"),
    OfflineDuaItem(71, "অমুসলিমদের সালামের জবাব", "dua_071.html"),
    OfflineDuaItem(72, "অন্তর কে পাপ কাজ থেকে বাঁচিয়ে রাখার দো'আ", "dua_072.html"),
    OfflineDuaItem(73, "অন্তর কে সব সময় আল্লাহ্‌র আনুগত্যে রাখার দো'আ", "dua_073.html"),
    OfflineDuaItem(74, "দরজা-জানালা বন্ধ করা এবং যে কোন খাদ্যদ্রব্য ঢাকার", "dua_074.html"),
    OfflineDuaItem(75, "সময় দো'আ", "dua_075.html"),
    OfflineDuaItem(76, "তিলাওয়াতকারী ও শ্রোতাদের আয়াতের জবাব", "dua_076.html"),
    OfflineDuaItem(77, "ছালাতে বা বাইরে)", "dua_077.html"),
    OfflineDuaItem(78, "কতিপয় গুরুত্বপূর্ণ সূরা ও আয়াতের ফযীলত", "dua_078.html"),
    OfflineDuaItem(79, "মুমূর্ষু ব্যক্তির নিকট পঠিতব্য দো'আ", "dua_079.html"),
    OfflineDuaItem(80, "পিতা-মাতার জন্য দো'আ", "dua_080.html"),
    OfflineDuaItem(81, "দুঃখ-কষ্টের সময় পঠিতব্য দো'আ", "dua_081.html"),
    OfflineDuaItem(82, "সন্তান ও পরিবারের জন্য দো'আ", "dua_082.html"),
    OfflineDuaItem(83, "সুসন্তান প্রার্থনার দো'আ", "dua_083.html"),
    OfflineDuaItem(84, "কারো বিদ্যা-বুদ্ধির জন্য দো'আ", "dua_084.html"),
    OfflineDuaItem(85, "অন্যের মাধ্যমে সালাম পাঠালে তার উত্তর", "dua_085.html"),
    OfflineDuaItem(86, "আল্লাহ্‌র গুণবাচক নাম সমূহ", "dua_086.html"),
    OfflineDuaItem(87, "তাহাজ্জুদ ছলাতের পূর্বে তেলাওয়াত ও তাসবীহ", "dua_087.html"),
    OfflineDuaItem(88, "জান্নাত চাওয়া ও জাহান্নাম হ'তে বাঁচার দো'আ", "dua_088.html"),
    OfflineDuaItem(89, "ইদায়নের তাকবীর বা দো'আ", "dua_089.html"),
    OfflineDuaItem(90, "হজ্জ ও ওমরাহ পালনকারী মুহরিম ব্যক্তির তালবিয়া", "dua_090.html"),
    OfflineDuaItem(91, "রুকনে ইয়ামনী এবং হাজারে আসওয়াদের মাঝে দো'আ", "dua_091.html"),
    OfflineDuaItem(92, "আরাফার মাঠে দো'আ", "dua_092.html"),
    OfflineDuaItem(93, "মাশ'আরে হারামের নিকট যিকির", "dua_093.html"),
    OfflineDuaItem(94, "পাথর নিক্ষেপের সময় তাকবীর", "dua_094.html"),
    OfflineDuaItem(95, "কুরবানীর দো'আ", "dua_095.html"),
    OfflineDuaItem(96, "আয়না দেখার দো'আ", "dua_096.html"),
    OfflineDuaItem(97, "রাসূল (ছাঃ)-এর প্রতি দরূদ পাঠের ফযীলত", "dua_097.html"),
    OfflineDuaItem(98, "ছালাতের মাঝে শয়তানের কুমন্ত্রণা হ'তে বাঁচার দো'আ", "dua_098.html"),
    OfflineDuaItem(99, "কুনূতে রাতিবা বা বিতর-এর কুনূত", "dua_099.html"),
    OfflineDuaItem(100, "ইস্তেখারার নিয়ম ও দো'আ", "dua_100.html"),
    OfflineDuaItem(101, "তাসবীহ, তাহমীদ, তাহলীল ও তাকবীর", "dua_101.html"),
    OfflineDuaItem(102, "হাত তুলে দো'আর প্রমাণে পেশকৃত যঈফ হাদীছ সমূহ", "dua_102.html"),
    OfflineDuaItem(103, "(পরফ:১)", "dua_103.html"),
    OfflineDuaItem(104, "ফরয ছালাতের পরে সম্মিলিতভাবে হাত তুলে দো'আ সম্বন্ধে", "dua_104.html"),
    OfflineDuaItem(105, "রব্বানা তাকাব্বাল মিন্না দো'আ", "dua_105.html"),
    OfflineDuaItem(106, "পৃথিবীর শ্রেষ্ঠ আলেমগণের অভিমত", "dua_106.html"),
    OfflineDuaItem(107, "রব্বানা লা তুযিগ কুলুবানা দো'আ", "dua_107.html"),
    OfflineDuaItem(108, "যে সকল স্থানে হাত তুলে দো'আ করা যায়", "dua_108.html"),
    OfflineDuaItem(109, "রব্বানা আমান্না ফাগফির লানা দো'আ", "dua_109.html"),
    OfflineDuaItem(110, "রব্বানা লা তুআখিযনা দো'আ", "dua_110.html"),
    OfflineDuaItem(111, "রব্বানা লা তুহাম্মিলনা দো'আ", "dua_111.html"),
    OfflineDuaItem(112, "রব্বানা ওয়ালা তুহাম্মিলনা মা লা ত্বাক্বাতা দো'আ", "dua_112.html"),
    OfflineDuaItem(113, "রব্বানা আফরিগ আলাইনা সবরান দো'আ", "dua_113.html"),
    OfflineDuaItem(114, "রব্বানা ইফতাহ বাইনানা দো'আ", "dua_114.html"),
    OfflineDuaItem(115, "রব্বি ইন্নি যালামতু নাফসি দো'আ", "dua_115.html"),
    OfflineDuaItem(116, "রব্বি ইন্নি লিমা আনযালতা ইলাইয়া দো'আ", "dua_116.html"),
    OfflineDuaItem(117, "রব্বি ইশরাহ লি সদরি দো'আ", "dua_117.html"),
    OfflineDuaItem(118, "রব্বি যিদনি ইলমা দো'আ", "dua_118.html"),
    OfflineDuaItem(119, "রব্বি লা তাযারনি ফারদান দো'আ", "dua_119.html"),
    OfflineDuaItem(120, "রব্বি হাব লি মিনাস সালিহীন দো'আ", "dua_120.html"),
    OfflineDuaItem(121, "রব্বি আউযু বিকা মিন হামাযাতিশ শায়াতীন দো'আ", "dua_121.html"),
    OfflineDuaItem(122, "রব্বি আউযু বিকা আন আসআলাকা দো'আ", "dua_122.html"),
    OfflineDuaItem(123, "রব্বি আউযু বিকা মিনাল হাম্মি ওয়াল হাযান দো'আ", "dua_123.html"),
    OfflineDuaItem(124, "আল্লাহুম্মা ইন্নি আসআলুকাল হুদা দো'আ", "dua_124.html"),
    OfflineDuaItem(125, "আল্লাহুম্মা ইন্নি আসআলুকাল ইলমা নাফিআ দো'আ", "dua_125.html"),
    OfflineDuaItem(126, "আল্লাহুম্মা ইন্নি যালামতু নাফসি দো'আ", "dua_126.html"),
    OfflineDuaItem(127, "সাইয়্যিদুল ইস্তিগফার দো'আ", "dua_127.html"),
    OfflineDuaItem(128, "আল্লাহুম্মা ইন্নাকা আফুউন দো'আ", "dua_128.html"),
    OfflineDuaItem(129, "আল্লাহুম্মা ইন্নি আসআলুকা মিনাল খাইরি কুল্লিহি দো'আ", "dua_129.html"),
    OfflineDuaItem(130, "আল্লাহুম্মা ইন্নি আসআলুকা মুজিবাতি রহমাতিক দো'আ", "dua_130.html"),
    OfflineDuaItem(131, "আল্লাহুম্মা আউযু বিকা মিন ইলমিন লা ইয়ানফা দো'আ", "dua_131.html"),
    OfflineDuaItem(132, "আল্লাহুম্মা আউযু বিকা মিনাল ফিতনাহ দো'আ", "dua_132.html"),
    OfflineDuaItem(133, "আল্লাহুম্মা ইন্নি আউযু বিকা মিনাল কাসাল দো'আ", "dua_133.html"),
    OfflineDuaItem(134, "আল্লাহুম্মা আউযু বিকা মিনাল মাআসাম দো'আ", "dua_134.html"),
    OfflineDuaItem(135, "ঋণ পরিশোধের দো'আ", "dua_135.html"),
    OfflineDuaItem(136, "আল্লাহুম্মা ইন্নি আসআলুকাল আফওয়া ওয়াল আফিয়াহ দো'আ", "dua_136.html"),
    OfflineDuaItem(137, "আল্লাহুম্মা ইন্নি আসআলুকা হুসনাল খাতিমাহ দো'আ", "dua_137.html"),
    OfflineDuaItem(138, "মুসিবতে ইন্না লিল্লাহ দো'আ", "dua_138.html"),
    OfflineDuaItem(139, "রোগমুক্তির দো'আ", "dua_139.html"),
    OfflineDuaItem(140, "রোগীর জন্য সাতবারের দো'আ", "dua_140.html"),
    OfflineDuaItem(141, "খাবার শুরুর দো'আ", "dua_141.html"),
    OfflineDuaItem(142, "খাবার ভুলে বিসমিল্লাহ না বললে দো'আ", "dua_142.html"),
    OfflineDuaItem(143, "খাবার শেষে দো'আ", "dua_143.html"),
    OfflineDuaItem(144, "পানীয় পান করানোর পর দো'আ", "dua_144.html"),
    OfflineDuaItem(145, "হাঁচির জবাবের দো'আ", "dua_145.html"),
    OfflineDuaItem(146, "হাঁচির পর নিজের দো'আ", "dua_146.html"),
    OfflineDuaItem(147, "হাঁচির জবাবের পর ভাইয়ের জন্য দো'আ", "dua_147.html"),
    OfflineDuaItem(148, "বজ্রপাতের সময় দো'আ", "dua_148.html"),
    OfflineDuaItem(149, "বৃষ্টির সময় দো'আ", "dua_149.html"),
    OfflineDuaItem(150, "বৃষ্টি বেশি হলে দো'আ", "dua_150.html"),
    OfflineDuaItem(151, "বৃষ্টি শেষে দো'আ", "dua_151.html"),
    OfflineDuaItem(152, "ভ্রমণে রওনা হওয়ার দো'আ", "dua_152.html"),
    OfflineDuaItem(153, "সফর থেকে ফেরার দো'আ", "dua_153.html"),
    OfflineDuaItem(154, "বাজারে প্রবেশের দো'আ", "dua_154.html"),
    OfflineDuaItem(155, "বাজারে প্রতারণা থেকে বাঁচার নসিহত ও দো'আ", "dua_155.html"),
    OfflineDuaItem(156, "মসজিদে প্রবেশের অতিরিক্ত দো'আ", "dua_156.html"),
    OfflineDuaItem(157, "মসজিদ থেকে বের হওয়ার দো'আ", "dua_157.html"),
    OfflineDuaItem(158, "ঘর থেকে বের হওয়ার অতিরিক্ত দো'আ", "dua_158.html"),
    OfflineDuaItem(159, "নতুন পোশাকের প্রশংসা ও দো'আ", "dua_159.html"),
    OfflineDuaItem(160, "বিবাহের পর স্বামী-স্ত্রীর জন্য দো'আ", "dua_160.html"),
    OfflineDuaItem(161, "সহবাসের আগে দো'আ", "dua_161.html"),
    OfflineDuaItem(162, "ইস্তেখারার পর কল্যাণের দো'আ", "dua_162.html"),
)